export default {
  id: "unikey",
  priority: 75,
  alias: "yk",
  aliases: [
    "getunikey",
    "guk",
    "uk",
  ],
  uiAlias: "yk",
  display: {
    name: "UniKey",
    icon: "key",
    color: "#6366F1",
    textIcon: "YK",
    website: "https://www.getunikey.ai",
    notice: {
      text: "OpenAI-compatible gateway (New-API). Chat Completions via Bearer API key.",
      apiKeyUrl: "https://www.getunikey.ai",
    },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://www.getunikey.ai/v1/chat/completions",
    validateUrl: "https://www.getunikey.ai/v1/models",
    thinkingFormat: "openai",
  },
  // Curated chat-safe seed (MODELS.md 2026-07-22). Live catalogue via modelsFetcher;
  // passthroughModels accepts any id returned by GET /v1/models.
  models: [
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6", name: "GPT-5.6" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "x-ai/grok-4.3", name: "Grok 4.3" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "z-ai/glm-5.2", name: "GLM 5.2" },
    { id: "z-ai/glm-5.1", name: "GLM 5.1" },
    { id: "z-ai/glm-5-turbo", name: "GLM 5 Turbo" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen/qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "qwen/qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen/qwen3.6-flash", name: "Qwen3.6 Flash" },
  ],
  serviceKinds: ["llm", "imageToText"],
  modelsFetcher: { url: "https://www.getunikey.ai/v1/models", type: "openai" },
  passthroughModels: true,
};
